### ISSUE TITLE
 libwcs4 : Depends: pgplot5 but it is not installable

### ISSUE THREAD

**Issue by o-smirnov** [radio-astro/packaging#11]
Brand new install on a fresh 14.04 VM, I can't get libcasacore2 because it depends on libwcs4 because it depends on the above which is nowhere to be found.

**Comment by gijzelaerr** [comment]
Enable universe and multiverse

Op zo 6 sep. 2015 12:12 schreef Oleg Smirnov notifications@github.com:

**Comment by o-smirnov** [comment]
Yep, that solves it. Could you add a note about this to the README please?

How did casarest manage to install, is not dependent on libcasacore2?

**Comment by gijzelaerr** [comment]
What readme? Casarest uuuhm i dint know, should depend on casacore

Op zo 6 sep. 2015 12:16 schreef Oleg Smirnov notifications@github.com:

**Comment by o-smirnov** [comment]
The one I just edited. :) Well it doesn't depend on casacore as I just found out.

**Comment by gijzelaerr** [comment]
Weird. Debian packaging logic should auto add depending dependencies. Maybe
some weird casa thing that it doesn't pick it up. If you open an issue on
the casa rest Debian package thing I'll fix it when I have the time

Op zo 6 sep. 2015 12:23 schreef Oleg Smirnov notifications@github.com:

**Comment by o-smirnov** [comment]
Where's casarest-debian?

**Comment by o-smirnov** [comment]
I mean the repo?

**Comment by gijzelaerr** [comment]
Github.com/radio-astro-debian/casarest-debian I think
Op 6 sep. 2015 12:28 PM schreef "Oleg Smirnov" notifications@github.com:

**Comment by gijzelaerr** [comment]
casacore dep issue has been solved per

https://github.com/radio-astro-debian/casarest-debian/commit/1a496efa448066f27a5b7f4d93bbe8a5ae5e0d3c

doc has been updated by oleg, we can close this issue.
