### ISSUE TITLE
Remove casacore 1.7 and pyrap from the PPA

### ISSUE THREAD

**Issue by o-smirnov** [radio-astro/packaging#13]
I've managed to create an unholy mess when I had the above combination of packages installed. In particular, I could no longer build a working meqtrees -- the meqserver segfaulted instantly. I believe the root cause was that it was linking to casacore1 libraries for everything except libcasa_components, which it took from casarest, which linked in casacore2, which caused it all to fall down.

Now possibly this is really a meqtrees cmake issue that needs to be sorted out. However, I must question, do we really need to keep libcasacore1 around at this point? I think only aoflagger still depends on it, and I'm guessing it can easily be rebuilt against libcasacore2. Apart from that, having the two versions coexist seems to cause too much confusion.

So, if nothing else needs libcasacore1, can we consider killing it off silently?

**Comment by tammojan** [comment]
I think it should not be necessary to have casacore 1 and 2 next to each other.

**Comment by gijzelaerr** [comment]
i didnt' really indent it as a feature. I just started with adding a casacore2 package and then slow recompiled everything without making them interfere. 

when all packages are compiled with casacore2 we can indeed move casacore 1.7 if you ask me. so only aoflagger requires a recompile you say?

**Comment by o-smirnov** [comment]
I think it's aoflagger, wsclean and oskar that need rebuilding. Then, python-pyrap can be retired too (since python-casacore provides the same), and lwimager too as soon as you've rolled a new casarest. What's a quick way to check if anything else depends on it?

**Comment by tammojan** [comment]
Let's not retire lwimager, since the new Casasynthesis does not provide an executable interface.

**Comment by o-smirnov** [comment]
But casarest contains an lwimager executable. I've made a pull request for
my small changes to it.

**Comment by tammojan** [comment]
Moreover, there is no problem for Casarest and Casasynthesis to coexist (actually we need that for lofar, where awimager2 and awimager coexist).

**Comment by tammojan** [comment]
> But casarest contains an lwimager executable. 

Do you mean Casasynthesis?

**Comment by o-smirnov** [comment]
No, I do mean casarest...

**Comment by tammojan** [comment]
Ok, got it (I hope). You want to retire [lwimager](https://github.com/ska-sa/lwimager) because [casarest](https://github.com/casacore/casarest) is basically the same?

**Comment by o-smirnov** [comment]
Yep.

**Comment by gijzelaerr** [comment]
will update aoflagger at the same time https://github.com/radio-astro/packaging/issues/17

**Comment by gijzelaerr** [comment]
some for oskar https://github.com/radio-astro/packaging/issues/18

**Comment by gijzelaerr** [comment]
OK last remaing dependencies are:

```
$  apt-cache rdepends libcasacore1
Reverse Depends:
  mt-imager
  sagecal
  casacore1.3-static
  wsclean
```

@o-smirnov do you still need to static 1.3? Probably the other packages should be updated, right?

**Comment by o-smirnov** [comment]
I don't need static 1.3. Didn't know we were keeping it around in the first place -- can't imagine what for -- any record of that in the reverse dependencies?

The rest should just be updated & rebuilt. In case of problems we tag Daniel and Andre and Sarod.

**Comment by gijzelaerr** [comment]
everthing has been rebuild, casacore 1.7 and pyrap have been removed.
