### ISSUE TITLE
lwimager version

### ISSUE THREAD

**Issue by TariqBlecher** [radio-astro/packaging#16]
The default lwimager version when running from im.lwimager doesn't have the predict_vis function and when lwimager-1.2 is installed, I'm not sure how to change the lwimager path so that it finds lwimager-1.2 instead.

2015/09/18 11:04:37 ABORT: lwimager 1.3.0 cannot be used to predict visibilities. Try lwimager-1.2, or upgrade to 1.3.2 or higher

**Comment by gijzelaerr** [comment]
is this a packaging issue?

**Comment by TariqBlecher** [comment]
I thought it might originate with the casarest version that the packing
installs

**Comment by gijzelaerr** [comment]
Sorry but I'm not sure what to make of this.
