### ISSUE TITLE
casarest: make a static lwimager

### ISSUE THREAD

**Issue by gijzelaerr** [radio-astro/packaging#19]
currently casarest conflict with casasynthesis, since they both install casasynthesis libraries. We can probably solve this by making a static lwimager library containing all the casasynthesis libraries, and don't install the synthesis related stuff in the casarest pacakge.

https://github.com/casacore/casarest

**Comment by tammojan** [comment]
They should not conflict (and do not in my installation). Casasynthesis installs libsynthesis.so , casarest installs libcasa_synthesis.so

**Comment by gijzelaerr** [comment]
oooo that is actually good news.

**Comment by gijzelaerr** [comment]
yes, we can install install both casarest and casasynthesis packages at the same time.
