### ISSUE TITLE
python-pyrap is missing

### ISSUE THREAD

**Issue by sphemakh** [radio-astro/packaging#23]
Pyrap is no longer in the ppa.

**Comment by gijzelaerr** [comment]
This is intended, use python-casacore

Op ma 12 okt. 2015 15:35 schreef Sphesihle Makhathini <
notifications@github.com>:

**Comment by sphemakh** [comment]
Cool

**Comment by sphemakh** [comment]
Maybe you should update the radio-astro docker images?

**Comment by gijzelaerr** [comment]
Yeah many things require an update and some sweet automation love. Will do
In november

Op ma 12 okt. 2015 17:28 schreef Sphesihle Makhathini <
notifications@github.com>:

**Comment by sphemakh** [comment]
![packaging](https://cloud.githubusercontent.com/assets/6624280/10431979/944a0dea-7108-11e5-8d25-6fd35d835701.png)
