### ISSUE TITLE
Update MeqTrees and related packages

### ISSUE THREAD

**Issue by sphemakh** [radio-astro/packaging#25]
Could we update the following packages with their respective github versions
- MeqTrees Timba
- Cattery
- Owlact
- Pyxis

**Comment by gijzelaerr** [comment]
made new releases and packages:

https://github.com/ska-sa/meqtrees-timba/releases/tag/v1.5.0
https://launchpad.net/~radio-astro/+archive/ubuntu/main/+build/8864372

https://github.com/ska-sa/meqtrees-cattery/releases/tag/1.4.0
https://launchpad.net/~radio-astro/+archive/ubuntu/main/+build/8838221

https://github.com/ska-sa/owlcat/releases/tag/v1.4.0
https://launchpad.net/~radio-astro/+archive/ubuntu/main/+build/8846427

https://github.com/ska-sa/pyxis/releases/tag/v1.4.4
https://launchpad.net/~radio-astro/+archive/ubuntu/main/+build/8864498
