### ISSUE TITLE
aoflagger comes without shared library

### ISSUE THREAD

**Issue by gmloose** [radio-astro/packaging#26]
I noticed that the aoflagger package does not contain a shared library. I need a shared library, because the AOFlagger is loaded as a module in the LOFAR DPPP software. Would it be possible to add a shared library as well? I think it suffices to add the cmake command-line option `-DBUILD_SHARED_LIBS=ON` to accomplish this.

One thing to consider. The current CMakeLists.txt files sets "-march=native" if the compiler supports it. I think it undesirable to use this option for a distributable package. You can force CMake to not add this option by adding the command-line option `-DCOMPILER_SUPPORTS_MARCH_NATIVE=OFF`.

Besides that, I think it would be better if the AOFlagger build would use the standard build-types provided by CMake and not fiddle with compiler options itself. That, however, should be discussed with the author of the package, André Offringa.

**Comment by gijzelaerr** [comment]
About the `-march` flag, we already set that:

https://github.com/radio-astro-debian/aoflagger-debian/blob/trusty/rules#L8

When I add `-DBUILD_SHARED_LIBS=ON` to the debian rules the resulting binaries are missing shared libraries:

```
/usr/bin/aoquality: error while loading shared libraries: libaoflaggerremote.so: cannot open shared object file: No such file or directory
/usr/bin/aoqplot: error while loading shared libraries: libaoflaggergui.so: cannot open shared object file: No such file or directory
/usr/bin/rfigui: error while loading shared libraries: libaoflaggergui.so: cannot open shared object file: No such file or directory
/usr/bin/aoremoteclient: error while loading shared libraries: libaoflaggerremote.so: cannot open shared object file: No such file or directory
```

**Comment by gmloose** [comment]
Hi Gijs,

I'm no expert on building Debian packages, but I do know that the
AOFlagger build environment sets things up such that an RPATH is being
linked into the libraries and binaries. Maybe that's causing havoc here.
Could you please try again with the extra CMake command-line option
"-DCMAKE_SKIP_RPATH=ON". This will avoid RPATH being linked in.

Cheers,
Marcel.

**Comment by gijzelaerr** [comment]
Hoi Marcel,

Debian doet voor de rest niet zo veel, behalve de standaard cmake workflow
volgen. volgens mij heeft het er meer mee te maken dat de CMake files van
aoflagger de andere so files niet installeren. AOflagger lijkt er van uit
te gaan dat de andere libs statics in de statische lib worden gecompiled.
- Gijs

2016-01-25 14:10 GMT+02:00 Marcel Loose notifications@github.com:

> Hi Gijs,
> 
> I'm no expert on building Debian packages, but I do know that the
> AOFlagger build environment sets things up such that an RPATH is being
> linked into the libraries and binaries. Maybe that's causing havoc here.
> Could you please try again with the extra CMake command-line option
> "-DCMAKE_SKIP_RPATH=ON". This will avoid RPATH being linked in.
> 
> Cheers,
> Marcel.
> 
> On 22/01/16 14:41, Gijs Molenaar wrote:
> 
> > About the |-march| flag, we already set that:
> > 
> > https://github.com/radio-astro-debian/aoflagger-debian/blob/trusty/rules#L8
> > 
> > When I add |-DBUILD_SHARED_LIBS=ON| to the debian rules the resulting
> > binaries are missing shared libraries:
> > 
> > |/usr/bin/aoquality: error while loading shared libraries:
> > libaoflaggerremote.so: cannot open shared object file: No such file or
> > directory /usr/bin/aoqplot: error while loading shared libraries:
> > libaoflaggergui.so: cannot open shared object file: No such file or
> > directory /usr/bin/rfigui: error while loading shared libraries:
> > libaoflaggergui.so: cannot open shared object file: No such file or
> > directory /usr/bin/aoremoteclient: error while loading shared
> > libraries: libaoflaggerremote.so: cannot open shared object file: No
> > such file or directory |
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/radio-astro/packaging/issues/26#issuecomment-173924208
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/radio-astro/packaging/issues/26#issuecomment-174487216
> .

## 

Gijs Molenaar
http://pythonic.nl

**Comment by nudomarinero** [comment]
I would like to add that the current LOFAR data release (2.15) that has been announced today seems to require the AOflagger shared library.

**Comment by gijzelaerr** [comment]
aoflagger package has been updated to contain shared libraries and the lofar package has been updated to 2.15
