### ISSUE TITLE
pybdsm update

### ISSUE THREAD

**Issue by rdeane** [radio-astro/packaging#27]
Hi, 

Please could pybdsm be updated on jake and elwood when possible? It now includes enough digits in the output catalogues to do VLBI Soucery runs (and includes a bunch of other bug fixes apparently).

thanks

**Comment by gijzelaerr** [comment]
Pybdsm is part of lofar right? Which version do you require?
Op 25 jan. 2016 1:05 p.m. schreef "Roger Deane" notifications@github.com:

**Comment by rdeane** [comment]
Yip, but you can grab the latest version here: ftp://ftp.hs.uni-hamburg.de/pub/outgoing/rafferty/PyBDSM

I need version 1.8.5 or later please.

**Comment by gijzelaerr** [comment]
made new package for lofar (2.15.0) which contains pybdsm 1.8.6. please verify and reopen issue in case of problemos.
