### ISSUE TITLE
Oskar 2.6.1 failed to run on both elwood and jake

### ISSUE THREAD

**Issue by philusnarh** [radio-astro/packaging#30]
I*\* get this error when i run on elwood:**
E|  
E|== ERROR: Run failed: no CUDA-capable device is detected.
E|  
 |  
=|== OSKAR-2.6.1 ending at 2016-04-02, 19:25:46 (SAST).

**and when i try to run on jake, i get:**

E|  
E|== ERROR: Run failed: invalid device function .
E|  
 |  
=|== OSKAR-2.6.1 ending at 2016-04-02, 19:12:04 (SAST).

**Comment by philusnarh** [comment]
OSKAR-2.6.1 is running properly on elwood but failed to run on jake. Still complains about **'invalid device function'** . See error message below:

=|== Starting simulation...
 |  
 |   - Chunk  1/64, Time  1/24, Channel 1/1 [GPU 0]
 |  
=|== Final memory usage
 |  
 | + Memory on GPU 1 [Tesla K10.G2.8GB] is 1.5% (0.1/3.5 GB) used.
 |  
=|== Simulation timing
 |  
 | + Total wall time      : 0.843 s
 | + Load                 : 0.841 s
 | + Compute              : 0.001 s [GPU 0]
 | + Write                : 0.000 s
E|  
E|== ERROR: Run failed: invalid device function .
E|  
 |  
=|== OSKAR-2.6.1 ending at 2016-04-17, 20:52:59 (SAST).
 |

**Comment by gijzelaerr** [comment]
I think jake needs to be rebooted .@o-smirnov  ?

**Comment by gijzelaerr** [comment]
closing this issue, since it is not a packaging issue.
