### ISSUE TITLE
Need to ship debug symbols for casacore and python-casacore

### ISSUE THREAD

**Issue by o-smirnov** [radio-astro/packaging#31]
Debian seems to have a standard way for this, see e.g. `python-numpy` and `python-numpy-dbg`, which can happily co-exist on the same system. Could we do something similar for [python-]casacore?

**Comment by gijzelaerr** [comment]
yah that is actually quite easy

https://github.com/radio-astro-debian/casacore-debian/commit/6588d7aac10537199e734603b0291f7d8c134858

https://launchpad.net/~radio-astro/+archive/ubuntu/main/+build/9541368
