### ISSUE TITLE
Not able to install pgplot5

### ISSUE THREAD

**Issue by sphemakh** [radio-astro/packaging#5]
I get a `pgplot5 has no installation candidates` when trying to install pgplot5. Which sucks since everything kinda depends on it. I eventually got it from [here](http://mirrors.kernel.org/ubuntu/pool/multiverse/p/pgplot5/pgplot5_5.2.2-19ubuntu1_amd64.deb)

**Comment by gijzelaerr** [comment]
what do you mean, it is in the multiverse archive. Did you enable universe and multiverse and the system you are using.

**Comment by gijzelaerr** [comment]
make sure that `/etc/apt/sources.list` looks something like this:

```
deb http://archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse
deb-src http://archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse
```

**Comment by sphemakh** [comment]
Ahh, multiverse was commented out out for some reason.
