### ISSUE TITLE
Missing dependencies for lofar package

### ISSUE THREAD

**Issue by ygrange** [radio-astro/packaging#6]
Hi,

I tried getting the lofar package to work on a cloud system. It worked quite well apart from three dependencies that are not solved by the package manager.

To be able to use ndppp, I needed to also install the package casacore-data. To be able to use bbs in the way demonstrated by the LOFAR imaging cookbook (the example chapter), python-pyrap was needed (although using bbs with pyrap conflicts with using awimager later on in this install). Then to run awimager, I needed to install the lwimager. 

So I would assume that those three packages should be installed as depenencies to the lofar package.

**Comment by ygrange** [comment]
For pybdsm the following packages are also needed:

ipython
python-pyfits
python-scipy
(and matplotlib if one wants to plot but this is not a hard dependence)

**Comment by gijzelaerr** [comment]
this has been fixed in the 2.11.1 package.
