### ISSUE TITLE
NDPPP version Unknown

### ISSUE THREAD

**Issue by ygrange** [radio-astro/packaging#7]
Hi,

I was asked which version of NDPPP I was using when I asked for support. The version from the repository does however not show any version information...
It shows:
"
NDPPP: version = Unknown (in CMakeLists.txt: 1.0)
 overall revision  = Unknown
 package revision  = Unknown (last change in package)
 built on lgw01-16 by buildd at Jan 27 2015 11:06:05
  Unknown files were different from the repository
"

**Comment by gijzelaerr** [comment]
I think this is a bug in the LOFAR software itself, since it probably looks at the svn details in the install/build directory. Will report this upstream and see what happens, thanks.

**Comment by tammojan** [comment]
At cmake time, the version info is pulled from the svn info of the source directory. Could you sketch your environment at cmake time?

**Comment by gijzelaerr** [comment]
well, I do an svn export and create a tarball which is used for creating
the debian packages. So this information is unfortunately lost. But you
don't want to have version control files in a release tarball.

2015-04-07 15:41 GMT+02:00 tammojan notifications@github.com:

> At cmake time, the version info is pulled from the svn info of the source
> directory. Could you sketch your environment at cmake time?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/radio-astro/packaging/issues/7#issuecomment-90557397.

## 

Gijs Molenaar
http://pythonic.nl

**Comment by tammojan** [comment]
I'm not sure the version number is stored somewhere hardcoded in the code as a fallback if svn does not work. Could you make a redmine ticket? (Subtracker LOFAR Scrum)

**Comment by tammojan** [comment]
Reported at https://support.astron.nl/lofar_issuetracker/issues/7731 (login required)

**Comment by tammojan** [comment]
Until this is fixed properly, you could set the svn revision number by hand with this small patch:

```
LOFAR_SVN_REV=svn info https://svn.astron.nl/LOFAR | sed -n 's/Revision: \([0-9]*\)/\1/p'
sed -i “s/rvers \"Unknown\"/rvers \"$LOFAR_SVN_REV\”/“ CMake/UpdatePackageVersion.cmake.in
```

**Comment by gijzelaerr** [comment]
@tammojan  This will use the rev number of the last commit right? That doesn't match the rev number of that specific tag of branch.

**Comment by tammojan** [comment]
@gijsmolenaar Correct. But basically, you can put any informative string there.

**Comment by gijzelaerr** [comment]
setting it to the latest svn revision as useless as leaving it as it is now
:) Probably good idea to force set it to a specific version.

but it looks like people want to solve this upstream right? if so I just
wait for that.

2015-05-04 15:02 GMT+02:00 Tammo Jan Dijkema notifications@github.com:

> @gijsmolenaar Correct. But basically, you can put any informative string
> there.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/radio-astro/packaging/issues/7#issuecomment-98699877.

## 

Gijs Molenaar
http://pythonic.nl

**Comment by tammojan** [comment]
Due to this bug I have no idea which branch or tag you are building. I
assumed the latest revision but apparently not.

Op 4 mei 2015 om 15:06 heeft Gijs Molenaar notifications@github.com het
volgende geschreven:

setting it to the latest svn revision as useless as leaving it as it is now
:) Probably good idea to force set it to a specific version.

but it looks like people want to solve this upstream right? if so I just
wait for that.

2015-05-04 15:02 GMT+02:00 Tammo Jan Dijkema notifications@github.com:

> @gijsmolenaar Correct. But basically, you can put any informative string
> there.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/radio-astro/packaging/issues/7#issuecomment-98699877.

## 

Gijs Molenaar
http://pythonic.nl

**Comment by gijzelaerr** [comment]
hi @ygrange,

What does the NDPPP version actually tell you? Why not look at the version number of the package?

```
$ dpkg -l | grep lofar
ii  lofar          2.11.1-1trusty            amd64        offline LOFAR user software
```

**Comment by ygrange** [comment]
Good question (the VM with the install I was talking about doesn't exist anymore). I am happy with any solution that makes it possible to discuss issues I encounter with people who support me (like @tammojan ) so the question for him would be: does that version number help?

**Comment by gijzelaerr** [comment]
@tammojan do you know what the status of this is? I lost track of this.

**Comment by gijzelaerr** [comment]
so this is an Issue with the LOFAR software suite, not the packager. Issue has been reported upstream but not solved yet. Unfortunatly LOFAR bugtracker is private, and it looks like my accocunt is not working anymore. I'm closing this issue, @tammojan feel free to pick it up.
