### ISSUE TITLE
casacore troubles - trusty/amd64

### ISSUE THREAD

**Issue by the-herbivore** [radio-astro/packaging#8]
Hi,

There seems to be an issue with the "trusty" branch of your repository
(at least it looks that way from my perspective).

The "trusty" amd64 binary packages file [1] contains dependencies/references
to versions of 'libcasacore-dev' and 'casacore' that are seemingly not available,
and which don't correlate with versions specified in the "trusty" sources file [2].

Could this be double-checked, please?

Thanks!

[1] http://ppa.launchpad.net/radio-astro/main/ubuntu/dists/trusty/main/binary-amd64/Packages
[2] http://ppa.launchpad.net/radio-astro/main/ubuntu/dists/trusty/main/source/Sources

**Comment by gijzelaerr** [comment]
Hi! Thanks for reporting this issue. When I look at the Packages and Sources section for python-casacore it looks like this:

Packages section:

```
Package: python-casacore
Priority: extra
Section: python
Installed-Size: 3355
Maintainer: Gijs Molenaar <gijs@pythonic.nl>
Architecture: amd64
Version: 2.0.0-3trusty
Replaces: python-pyrap
Provides: python2.7-casacore
Depends: python (>= 2.7), python (<< 2.8), python:any (>= 2.7.1-0ubuntu2), libboost-python1.54.0, libc6 (>= 2.4), libcasacore2, libgcc1 (>= 1:4.1.1), libstdc++6 (>= 4.4.0), python-numpy
Filename: pool/main/p/python-casacore/python-casacore_2.0.0-3trusty_amd64.deb
Size: 573534
MD5sum: dfa3429ba0e936e2c81cedb9f577e942
SHA1: 6b7516d9495a4f9aaa56773d8cbd801a76e4f8d8
SHA256: 18a6f3f58832ab54b95fbf378dffd2629d54c40a1bca776783a05caffcb7d007
Description: python wrapper for casacore
Description-md5: ac14bbd4a2a634be461638e5a3b4c521
```

Sources section

```
Package: python-casacore
Binary: python-casacore
Version: 2.0.0-3trusty
Section: python
Maintainer: Gijs Molenaar <gijs@pythonic.nl>
Build-Depends: debhelper (>= 8.0.0), python-dev, libcasacore2-dev, casacore-data, python-setuptools, libboost-python-dev, libcfitsio3-dev
Architecture: any
Standards-Version: 3.9.2
Format: 3.0 (quilt)
Directory: pool/main/p/python-casacore
Files:
 93d1f86328be9443df3e281e2f5b25a0 190078 python-casacore_2.0.0.orig.tar.gz
 283a35c904dd7d75459629f04ec4e4b5 1720 python-casacore_2.0.0-3trusty.debian.tar.xz
 0b25590be639f293f005cec4659b14fa 1542 python-casacore_2.0.0-3trusty.dsc
Checksums-Sha1:
 fc027867a3bf5c9785356eb5328194de1204d9b9 190078 python-casacore_2.0.0.orig.tar.gz
 dd5e61db6ea09d7f57ef63ae13ed5dbbc3488ef0 1720 python-casacore_2.0.0-3trusty.debian.tar.xz
 a67e25d52f95adeade576f48dcc9cf20847423ac 1542 python-casacore_2.0.0-3trusty.dsc
Checksums-Sha256:
 05fcc7db24e342d6f2fcf891cddb7ce6dc002b9b8c80d141adcf7eeca540dade 190078 python-casacore_2.0.0.orig.tar.gz
 c79989217333eb57ccef2648423217ebb55a91038dd8fca6631cd9ade7354fde 1720 python-casacore_2.0.0-3trusty.debian.tar.xz
 f539187ce6d283bf6af4efcf8c8c1ac4c03e6ca0c67a751e88e6c7470e8e1329 1542 python-casacore_2.0.0-3trusty.dsc
Homepage: https://github.com/ska-sa/python-casacore
Package-List: python-casacore deb python extra arch=any
```

I don't see any dependencies on casacore 1.7. Are you sure you issued a `apt-get update` before installing the packages?

**Comment by the-herbivore** [comment]
Ah, thanks - we may not be installing the correct package(s) then!?

Below is the reference to the specific 1.7 version issue I was referring to (related to casacore)

---

("binaries")

Archive: trusty
Version: 14.04
Component: main
Origin: LP-PPA-radio-astro-main
Label: Main radio astronomy software archive
Architecture: amd64

Package: libcasacore-dev
Source: casacore
Priority: extra
Section: libdevel
Installed-Size: 11625
Maintainer: Gijs Molenaar gijs@pythonic.nl
Architecture: amd64
Version: 1.7.0-2trusty
Depends: libcasacore1 (= 1.7.0-2trusty), wcslib-dev
Filename: pool/main/c/casacore/libcasacore-dev_1.7.0-2trusty_amd64.deb
Size: 1501406
MD5sum: cc3ba6ff74b70123ce5ac3bba9ca7e4f
SHA1: 8595384f890f002993767e45a32d43334fcb18ce
SHA256: 4bd06cda373c06b047deb4e391b68cca1f20f89973422a8ab66766bdb8dd66fc
Description: A set of libraries derived from aips++
Description-md5: b7bf4b1275171187aab46204cafb524a

Package: casacore
Priority: extra
Section: libdevel
Installed-Size: 3526
Maintainer: Gijs Molenaar gijs@pythonic.nl
Architecture: amd64
Version: 1.7.0-2trusty
Depends: libcasacore1 (= 1.7.0-2trusty)
Filename: pool/main/c/casacore/casacore_1.7.0-2trusty_amd64.deb
Size: 614648
MD5sum: 8d72093b3d124242a6bbbf4994585e02
SHA1: b9b9effb375dab77ffeb1facbc99b39475cd6203
SHA256: dddcb7e99f04c8eb2279fa5c00886d2e33352a72311194f36047761830b56f45
Description: A set of libraries derived from aips++
Description-md5: b7bf4b1275171187aab46204cafb524a

---

("sources")

Archive: trusty
Version: 14.04
Component: main
Origin: LP-PPA-radio-astro-main
Label: Main radio astronomy software archive
Architecture: source

Package: casacore
Binary: libcasacore2-dev, casacore2, libcasacore2
Version: 2.0.3-2trusty
Section: libs
Maintainer: Gijs Molenaar gijs@pythonic.nl
Build-Depends: debhelper (>= 8.0.0), cmake, flex, bison, libblas-dev, liblapack-dev, libcfitsio3-dev (>= 3.181), wcslib-dev (>= 4.20), libfftw3-dev, gfortran, libncurses5-dev, libreadline6-dev | libreadline-gplv2-dev, casacore-data, libhdf5-dev | libhdf5-mpi-dev | libhdf5-mpich2-dev | libhdf5-openmpi-dev | libhdf5-serial-dev, python-numpy, libboost-python-dev
Architecture: any
Standards-Version: 3.9.2
Format: 3.0 (quilt)
Directory: pool/main/c/casacore
Files:
 32d0a4cd35e8c684e92db1195e8199f7 7250964 casacore_2.0.3.orig.tar.gz
 bf2e8619dd9c936e25fa4106d734cea0 2756 casacore_2.0.3-2trusty.debian.tar.xz
 d1795978e1045d4177432f47c9ffceee 1819 casacore_2.0.3-2trusty.dsc
Checksums-Sha1:
 61853f7ec6a8a797fe312c8dc903f53353be5bf6 7250964 casacore_2.0.3.orig.tar.gz
 502fdc9591a4907bef6ca9f18f21de28507814b4 2756 casacore_2.0.3-2trusty.debian.tar.xz
 a2d928f5a01ff9742b0540e19512f930ca61f8ec 1819 casacore_2.0.3-2trusty.dsc
Checksums-Sha256:
 44746633113e16f8daabb38c404d2b316b1acfd9304a4df91cb1849d2786d726 7250964 casacore_2.0.3.orig.tar.gz
 2c2c9bd45968a8d6dbdfda4b116c47adb61f140d3f2429d8a77b497e9c959c46 2756 casacore_2.0.3-2trusty.debian.tar.xz
 7e978d76468ae80baa9302411576c7eb4f20959c7b9b3b2874178790a29876c1 1819 casacore_2.0.3-2trusty.dsc
Homepage: http://code.google.com/p/casacore/
Package-List: casacore2 deb libdevel extra arch=any
 libcasacore2 deb libs extra arch=any
 libcasacore2-dev deb libdevel extra arch=any

**Comment by gijzelaerr** [comment]
yes, that package is still in the repository, but you can just install the
casacore 2 package right?

2015-08-24 1:14 GMT+02:00 the-herbivore notifications@github.com:

> Ah, we may not be installed the correct packages then!
> 
> Below is the reference to the specific 1.7 version issue I was referring
> 
> ## to (related to casacore)
> 
> ("binaries")
> 
> Archive: trusty
> Version: 14.04
> Component: main
> Origin: LP-PPA-radio-astro-main
> Label: Main radio astronomy software archive
> Architecture: amd64
> 
> Package: libcasacore-dev
> Source: casacore
> Priority: extra
> Section: libdevel
> Installed-Size: 11625
> Maintainer: Gijs Molenaar gijs@pythonic.nl
> Architecture: amd64
> Version: 1.7.0-2trusty
> Depends: libcasacore1 (= 1.7.0-2trusty), wcslib-dev
> Filename: pool/main/c/casacore/libcasacore-dev_1.7.0-2trusty_amd64.deb
> Size: 1501406
> MD5sum: cc3ba6ff74b70123ce5ac3bba9ca7e4f
> SHA1: 8595384f890f002993767e45a32d43334fcb18ce
> SHA256: 4bd06cda373c06b047deb4e391b68cca1f20f89973422a8ab66766bdb8dd66fc
> Description: A set of libraries derived from aips++
> Description-md5: b7bf4b1275171187aab46204cafb524a
> 
> Package: casacore
> Priority: extra
> Section: libdevel
> Installed-Size: 3526
> Maintainer: Gijs Molenaar gijs@pythonic.nl
> Architecture: amd64
> Version: 1.7.0-2trusty
> Depends: libcasacore1 (= 1.7.0-2trusty)
> Filename: pool/main/c/casacore/casacore_1.7.0-2trusty_amd64.deb
> Size: 614648
> MD5sum: 8d72093b3d124242a6bbbf4994585e02
> SHA1: b9b9effb375dab77ffeb1facbc99b39475cd6203
> SHA256: dddcb7e99f04c8eb2279fa5c00886d2e33352a72311194f36047761830b56f45
> Description: A set of libraries derived from aips++
> 
> ## Description-md5: b7bf4b1275171187aab46204cafb524a
> 
> ("sources")
> 
> Archive: trusty
> Version: 14.04
> Component: main
> Origin: LP-PPA-radio-astro-main
> Label: Main radio astronomy software archive
> Architecture: source
> 
> Package: casacore
> Binary: libcasacore2-dev, casacore2, libcasacore2
> Version: 2.0.3-2trusty
> Section: libs
> Maintainer: Gijs Molenaar gijs@pythonic.nl
> Build-Depends: debhelper (>= 8.0.0), cmake, flex, bison, libblas-dev,
> liblapack-dev, libcfitsio3-dev (>= 3.181), wcslib-dev (>= 4.20),
> libfftw3-dev, gfortran, libncurses5-dev, libreadline6-dev |
> libreadline-gplv2-dev, casacore-data, libhdf5-dev | libhdf5-mpi-dev |
> libhdf5-mpich2-dev | libhdf5-openmpi-dev | libhdf5-serial-dev,
> python-numpy, libboost-python-dev
> Architecture: any
> Standards-Version: 3.9.2
> Format: 3.0 (quilt)
> Directory: pool/main/c/casacore
> Files:
> 32d0a4cd35e8c684e92db1195e8199f7 7250964 casacore_2.0.3.orig.tar.gz
> bf2e8619dd9c936e25fa4106d734cea0 2756 casacore_2.0.3-2trusty.debian.tar.xz
> d1795978e1045d4177432f47c9ffceee 1819 casacore_2.0.3-2trusty.dsc
> Checksums-Sha1:
> 61853f7ec6a8a797fe312c8dc903f53353be5bf6 7250964 casacore_2.0.3.orig.tar.gz
> 502fdc9591a4907bef6ca9f18f21de28507814b4 2756
> casacore_2.0.3-2trusty.debian.tar.xz
> a2d928f5a01ff9742b0540e19512f930ca61f8ec 1819 casacore_2.0.3-2trusty.dsc
> Checksums-Sha256:
> 44746633113e16f8daabb38c404d2b316b1acfd9304a4df91cb1849d2786d726 7250964
> casacore_2.0.3.orig.tar.gz
> 2c2c9bd45968a8d6dbdfda4b116c47adb61f140d3f2429d8a77b497e9c959c46 2756
> casacore_2.0.3-2trusty.debian.tar.xz
> 7e978d76468ae80baa9302411576c7eb4f20959c7b9b3b2874178790a29876c1 1819
> casacore_2.0.3-2trusty.dsc
> Homepage: http://code.google.com/p/casacore/
> Package-List: casacore2 deb libdevel extra arch=any
> libcasacore2 deb libs extra arch=any
> libcasacore2-dev deb libdevel extra arch=any
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/radio-astro/packaging/issues/8#issuecomment-133955480
> .

## 

Gijs Molenaar
http://pythonic.nl

**Comment by the-herbivore** [comment]
We still need 'casacore' around for things I'm fairly sure.Is it possible to match the versions up, per below?
Thanks!

**Comment by gijzelaerr** [comment]
I don't understand your question. casacore 1.7 and casacore 2.0 are both
available in the repository.

2015-08-25 3:11 GMT+02:00 the-herbivore notifications@github.com:

> We still need 'casacore' around for things I'm fairly sure.Is it possible
> to match the versions up, per below?
> Thanks!
> From: Gijs Molenaar notifications@github.com
> To: radio-astro/packaging packaging@noreply.github.com
> Cc: the-herbivore the.herbivore@yahoo.com.au
> Sent: Monday, 24 August 2015, 17:57
> Subject: Re: [packaging] casacore troubles - trusty/amd64 (#8)
> 
> yes, that package is still in the repository, but you can just install the
> casacore 2 package right?
> 
> 2015-08-24 1:14 GMT+02:00 the-herbivore notifications@github.com:
> 
> > Ah, we may not be installed the correct packages then!
> > 
> > Below is the reference to the specific 1.7 version issue I was referring
> > 
> > ## to (related to casacore)
> > 
> > ("binaries")
> > 
> > Archive: trusty
> > Version: 14.04
> > Component: main
> > Origin: LP-PPA-radio-astro-main
> > Label: Main radio astronomy software archive
> > Architecture: amd64
> > 
> > Package: libcasacore-dev
> > Source: casacore
> > Priority: extra
> > Section: libdevel
> > Installed-Size: 11625
> > Maintainer: Gijs Molenaar gijs@pythonic.nl
> > Architecture: amd64
> > Version: 1.7.0-2trusty
> > Depends: libcasacore1 (= 1.7.0-2trusty), wcslib-dev
> > Filename: pool/main/c/casacore/libcasacore-dev_1.7.0-2trusty_amd64.deb
> > Size: 1501406
> > MD5sum: cc3ba6ff74b70123ce5ac3bba9ca7e4f
> > SHA1: 8595384f890f002993767e45a32d43334fcb18ce
> > SHA256: 4bd06cda373c06b047deb4e391b68cca1f20f89973422a8ab66766bdb8dd66fc
> > Description: A set of libraries derived from aips++
> > Description-md5: b7bf4b1275171187aab46204cafb524a
> > 
> > Package: casacore
> > Priority: extra
> > Section: libdevel
> > Installed-Size: 3526
> > Maintainer: Gijs Molenaar gijs@pythonic.nl
> > Architecture: amd64
> > Version: 1.7.0-2trusty
> > Depends: libcasacore1 (= 1.7.0-2trusty)
> > Filename: pool/main/c/casacore/casacore_1.7.0-2trusty_amd64.deb
> > Size: 614648
> > MD5sum: 8d72093b3d124242a6bbbf4994585e02
> > SHA1: b9b9effb375dab77ffeb1facbc99b39475cd6203
> > SHA256: dddcb7e99f04c8eb2279fa5c00886d2e33352a72311194f36047761830b56f45
> > Description: A set of libraries derived from aips++
> > 
> > ## Description-md5: b7bf4b1275171187aab46204cafb524a
> > 
> > ("sources")
> > 
> > Archive: trusty
> > Version: 14.04
> > Component: main
> > Origin: LP-PPA-radio-astro-main
> > Label: Main radio astronomy software archive
> > Architecture: source
> > 
> > Package: casacore
> > Binary: libcasacore2-dev, casacore2, libcasacore2
> > Version: 2.0.3-2trusty
> > Section: libs
> > Maintainer: Gijs Molenaar gijs@pythonic.nl
> > Build-Depends: debhelper (>= 8.0.0), cmake, flex, bison, libblas-dev,
> > liblapack-dev, libcfitsio3-dev (>= 3.181), wcslib-dev (>= 4.20),
> > libfftw3-dev, gfortran, libncurses5-dev, libreadline6-dev |
> > libreadline-gplv2-dev, casacore-data, libhdf5-dev | libhdf5-mpi-dev |
> > libhdf5-mpich2-dev | libhdf5-openmpi-dev | libhdf5-serial-dev,
> > python-numpy, libboost-python-dev
> > Architecture: any
> > Standards-Version: 3.9.2
> > Format: 3.0 (quilt)
> > Directory: pool/main/c/casacore
> > Files:
> > 32d0a4cd35e8c684e92db1195e8199f7 7250964 casacore_2.0.3.orig.tar.gz
> > bf2e8619dd9c936e25fa4106d734cea0 2756
> > casacore_2.0.3-2trusty.debian.tar.xz
> > d1795978e1045d4177432f47c9ffceee 1819 casacore_2.0.3-2trusty.dsc
> > Checksums-Sha1:
> > 61853f7ec6a8a797fe312c8dc903f53353be5bf6 7250964
> > casacore_2.0.3.orig.tar.gz
> > 502fdc9591a4907bef6ca9f18f21de28507814b4 2756
> > casacore_2.0.3-2trusty.debian.tar.xz
> > a2d928f5a01ff9742b0540e19512f930ca61f8ec 1819 casacore_2.0.3-2trusty.dsc
> > Checksums-Sha256:
> > 44746633113e16f8daabb38c404d2b316b1acfd9304a4df91cb1849d2786d726 7250964
> > casacore_2.0.3.orig.tar.gz
> > 2c2c9bd45968a8d6dbdfda4b116c47adb61f140d3f2429d8a77b497e9c959c46 2756
> > casacore_2.0.3-2trusty.debian.tar.xz
> > 7e978d76468ae80baa9302411576c7eb4f20959c7b9b3b2874178790a29876c1 1819
> > casacore_2.0.3-2trusty.dsc
> > Homepage: http://code.google.com/p/casacore/
> > Package-List: casacore2 deb libdevel extra arch=any
> > libcasacore2 deb libs extra arch=any
> > libcasacore2-dev deb libdevel extra arch=any
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/radio-astro/packaging/issues/8#issuecomment-133955480>
> > .
> 
> ## 
> 
> Gijs Molenaar
> http://pythonic.nl
> —
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/radio-astro/packaging/issues/8#issuecomment-134434920
> .

## 

Gijs Molenaar
http://pythonic.nl

**Comment by the-herbivore** [comment]
Apologies for the delay - I've been afk.

I think I've gotten to the bottom of this - it seems as though this may
likely boil down to being a bug in 'apt-get' for debian:jessie, specifically
the 'source' component.

We also have a script that autobuilds all of these various packages, so this added
another layer of complication, as far as troubleshooting was concerned.

Thanks for your quick responses - closing!

**Comment by the-herbivore** [comment]
Hi,

Just to clarify my initial point, specifically in relation to libcasacore-dev in this case, you can see from the output below that version two (2.0.3) has entries in both binary and source, whereas version 1 (1.7.0-2) does not, which is a problem for those wanting to use that specific version.

vagrant@debian-jessie:~$ grep -r 1.7.0-2trusty /var/lib 2>/dev/null
/var/lib/apt/lists/ppa.launchpad.net_radio-astro_main_ubuntu_dists_trusty_main_binary-amd64_Packages:Version: 1.7.0-2trusty
/var/lib/apt/lists/ppa.launchpad.net_radio-astro_main_ubuntu_dists_trusty_main_binary-amd64_Packages:Depends: libcasacore1 (= 1.7.0-2trusty), wcslib-dev
/var/lib/apt/lists/ppa.launchpad.net_radio-astro_main_ubuntu_dists_trusty_main_binary-amd64_Packages:Filename: pool/main/c/casacore/libcasacore-dev_1.7.0-2trusty_amd64.deb
/var/lib/apt/lists/ppa.launchpad.net_radio-astro_main_ubuntu_dists_trusty_main_binary-amd64_Packages:Version: 1.7.0-2trusty
/var/lib/apt/lists/ppa.launchpad.net_radio-astro_main_ubuntu_dists_trusty_main_binary-amd64_Packages:Depends: libcasacore1 (= 1.7.0-2trusty)
/var/lib/apt/lists/ppa.launchpad.net_radio-astro_main_ubuntu_dists_trusty_main_binary-amd64_Packages:Filename: pool/main/c/casacore/casacore_1.7.0-2trusty_amd64.deb
/var/lib/apt/lists/ppa.launchpad.net_radio-astro_main_ubuntu_dists_trusty_main_binary-amd64_Packages:Version: 1.7.0-2trusty
/var/lib/apt/lists/ppa.launchpad.net_radio-astro_main_ubuntu_dists_trusty_main_binary-amd64_Packages:Filename: pool/main/c/casacore/libcasacore1_1.7.0-2trusty_amd64.deb

debian-jessie:~$ grep -r 2.0.3-2trusty /var/lib 2>/dev/null
/var/lib/apt/lists/ppa.launchpad.net_radio-astro_main_ubuntu_dists_trusty_main_source_Sources:Version: 2.0.3-2trusty
/var/lib/apt/lists/ppa.launchpad.net_radio-astro_main_ubuntu_dists_trusty_main_source_Sources: bf2e8619dd9c936e25fa4106d734cea0 2756 casacore_2.0.3-2trusty.debian.tar.xz
/var/lib/apt/lists/ppa.launchpad.net_radio-astro_main_ubuntu_dists_trusty_main_source_Sources: d1795978e1045d4177432f47c9ffceee 1819 casacore_2.0.3-2trusty.dsc
/var/lib/apt/lists/ppa.launchpad.net_radio-astro_main_ubuntu_dists_trusty_main_source_Sources: 502fdc9591a4907bef6ca9f18f21de28507814b4 2756 casacore_2.0.3-2trusty.debian.tar.xz
/var/lib/apt/lists/ppa.launchpad.net_radio-astro_main_ubuntu_dists_trusty_main_source_Sources: a2d928f5a01ff9742b0540e19512f930ca61f8ec 1819 casacore_2.0.3-2trusty.dsc
/var/lib/apt/lists/ppa.launchpad.net_radio-astro_main_ubuntu_dists_trusty_main_source_Sources: 2c2c9bd45968a8d6dbdfda4b116c47adb61f140d3f2429d8a77b497e9c959c46 2756 casacore_2.0.3-2trusty.debian.tar.xz
/var/lib/apt/lists/ppa.launchpad.net_radio-astro_main_ubuntu_dists_trusty_main_source_Sources: 7e978d76468ae80baa9302411576c7eb4f20959c7b9b3b2874178790a29876c1 1819 casacore_2.0.3-2trusty.dsc
/var/lib/apt/lists/ppa.launchpad.net_radio-astro_main_ubuntu_dists_trusty_main_binary-amd64_Packages:Version: 2.0.3-2trusty
/var/lib/apt/lists/ppa.launchpad.net_radio-astro_main_ubuntu_dists_trusty_main_binary-amd64_Packages:Depends: libcasacore2 (= 2.0.3-2trusty), wcslib-dev
/var/lib/apt/lists/ppa.launchpad.net_radio-astro_main_ubuntu_dists_trusty_main_binary-amd64_Packages:Filename: pool/main/c/casacore/libcasacore2-dev_2.0.3-2trusty_amd64.deb
/var/lib/apt/lists/ppa.launchpad.net_radio-astro_main_ubuntu_dists_trusty_main_binary-amd64_Packages:Version: 2.0.3-2trusty
/var/lib/apt/lists/ppa.launchpad.net_radio-astro_main_ubuntu_dists_trusty_main_binary-amd64_Packages:Depends: libcasacore2 (= 2.0.3-2trusty)
/var/lib/apt/lists/ppa.launchpad.net_radio-astro_main_ubuntu_dists_trusty_main_binary-amd64_Packages:Filename: pool/main/c/casacore/casacore2_2.0.3-2trusty_amd64.deb
/var/lib/apt/lists/ppa.launchpad.net_radio-astro_main_ubuntu_dists_trusty_main_binary-amd64_Packages:Version: 2.0.3-2trusty
/var/lib/apt/lists/ppa.launchpad.net_radio-astro_main_ubuntu_dists_trusty_main_binary-amd64_Packages:Filename: pool/main/c/casacore/libcasacore2_2.0.3-2trusty_amd64.deb
