### ISSUE TITLE
need to remove dependencies on python-pyrap

### ISSUE THREAD

**Issue by o-smirnov** [radio-astro/packaging#9]
Meqtrees and pyxis are currently marked as depending on python-pyrap, which is exclusive with python-casacore and therefore prevents a whole bunch of other stuff from being installed.

Since everything seems to work fine with casacore2 now, I propose changing the dependency to python-casacore.

**Comment by gijzelaerr** [comment]
confirmed, forgot to update these.

**Comment by gijzelaerr** [comment]
actually it was only pyxis I forgot to update, meqtrees is depending on that package.

updated pyxis:

https://launchpad.net/~radio-astro/+archive/ubuntu/main/+build/7854861
https://github.com/radio-astro-debian/pyxis-debian/commit/f690a1257d03891b675df38258f45423d72bd2c6

should become available soon.
